%SENSORS File containing Vernier sensor calibration information
%   sensor = sdaq.Sensors.sensortype returns an object containing
%   calibration information for the specified sensor type. This object is
%   used with <a href="matlab:help sdaq.addSensor">addSensor</a> and <a href="matlab:help sdaq.getScaleFun">getScaleFun</a> to connect to and properly read
%   data from a sensor of that type.
%
%   <a href="matlab:properties(sdaq.Sensors)">Click here</a> for a list of sensor types.
%
%   Using <a href="http://blogs.mathworks.com/desktop/2007/04/27/tab-completion-will-save-your-fingers/">tab completion</a> is recommended in selecting the specific sensor
%   needed. To use tab completion, type the following:
%       sdaq.Sensors.
%   and press the Tab key. A list of all possible sensor types should pop
%   up. Navigate to the desired sensor and press Enter/Return, or type
%   additional letters to narrow down the list.
%
%   Example usage:
%       % Display calibration information for a thermocouple
%       sdaq.Sensors.Thermocouple
%
%       % Specify a thermocouple sensor when calling <a href="matlab:help sdaq.getScaleFun">getScaleFun</a>
%       scale = sdaq.getScaleFun(sdaq.Sensors.Thermocouple);
%
%   See also: sdaq.addSensor, sdaq.getScaleFun


    %   MATLAB Support Package for Vernier SensorDAQ
    %   Version 1.0
    %   Copyright 2011 The MathWorks, Inc.


%   Each sensor object is a struct containing the following fields:
%       Name - A descriptive name for the sensor
%       Channel - Which voltage channel the sensor used (5 or 10)
%       CalEq - What calibration equation the sensor uses
%       CalXConsts - Constants for calibration number X (X = 0, 1 or 2)
%       CalXUnits - Units for calibration number X (X = 0, 1 or 2)
%



classdef Sensors
properties(Constant)
	PH = struct(...
		'Name',            {'PH'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [13.72 -3.838 0],          ...
		'Cal0Units',       {''},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Conductivity200 = struct(...
		'Name',            {'Conductivity 200'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 65.7 0],          ...
		'Cal0Units',       {'(MICS)'},            ...
		'Cal1Consts',      [0 32.85 0],          ...
		'Cal1Units',       {'(MG/L)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Conductivity2000 = struct(...
		'Name',            {'Conductivity 2000'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 847.2 0],          ...
		'Cal0Units',       {'(MICS)'},            ...
		'Cal1Consts',      [0 423.6 0],          ...
		'Cal1Units',       {'(MG/L)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Conductivity20000 = struct(...
		'Name',            {'Conductivity 20000'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 7819 0],          ...
		'Cal0Units',       {'(MICS)'},            ...
		'Cal1Consts',      [0 3909 0],          ...
		'Cal1Units',       {'(MG/L)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	GasPressure = struct(...
		'Name',            {'Gas Pressure'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0.003 46.48 0],          ...
		'Cal0Units',       {'(KPA)'},            ...
		'Cal1Consts',      [0.024 348.63 0],          ...
		'Cal1Units',       {'(MMHG)'},            ...
		'Cal2Consts',      [3.00*10^-05 0.4587 0],          ...
		'Cal2Units',       {'(ATM)'})            ...

	DualRangeForce10N = struct(...
		'Name',            {'Dual-Range Force 10N'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [12.25 -4.9 0],          ...
		'Cal0Units',       {'(N)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	DualRangeForce50N = struct(...
		'Name',            {'Dual-Range Force 50N'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [61.25 -24.5 0],          ...
		'Cal0Units',       {'(N)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Accelerometer25g = struct(...
		'Name',            {'25-g Accelerometer'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-287.8 127.9 0],          ...
		'Cal0Units',       {'(m/s^2)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	LowgAccelerometer = struct(...
		'Name',            {'Low-g Accelerometer'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-51.751 22.924 0],          ...
		'Cal0Units',       {'(m/s^2)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	AccelerometerX3Axis = struct(...
		'Name',            {'3-Axis Accelerometer (X)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-51.751 22.924 0],          ...
		'Cal0Units',       {'(m/s^2)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	AccelerometerY3Axis = struct(...
		'Name',            {'3-Axis Accelerometer (Y)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-51.751 22.924 0],          ...
		'Cal0Units',       {'(m/s^2)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	AccelerometerZ3Axis = struct(...
		'Name',            {'3-Axis Accelerometer (Z)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-51.751 22.924 0],          ...
		'Cal0Units',       {'(m/s^2)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Microphone = struct(...
		'Name',            {'Microphone'},            ...
		'Channel',         10,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 1 0],          ...
		'Cal0Units',       {''},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	LightSensor600lux = struct(...
		'Name',            {'Light Sensor (600 lux)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 154 0],          ...
		'Cal0Units',       {'(LX)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	LightSensor6000lux = struct(...
		'Name',            {'Light Sensor (6000 lux)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 1692 0],          ...
		'Cal0Units',       {'(LX)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	LightSensor150000lux = struct(...
		'Name',            {'Light Sensor (150000 lux)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 38424 0],          ...
		'Cal0Units',       {'(LX)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	DissolvedOxygen = struct(...
		'Name',            {'Dissolved Oxygen'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-0.327 3.27 0],          ...
		'Cal0Units',       {'(MG/L)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	FlowRate = struct(...
		'Name',            {'Flow Rate'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 1 0],          ...
		'Cal0Units',       {'(M/S)'},            ...
		'Cal1Consts',      [0 3.28 0],          ...
		'Cal1Units',       {'(FT/S)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Turbidity = struct(...
		'Name',            {'Turbidity'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-80 150 0],          ...
		'Cal0Units',       {'(NTU)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	MagneticFieldHI = struct(...
		'Name',            {'Magnetic Field (HI)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-0.32 0.16 0],          ...
		'Cal0Units',       {'(MT)'},            ...
		'Cal1Consts',      [-3.2 1.6 0],          ...
		'Cal1Units',       {'(G)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	MagneticFieldLO = struct(...
		'Name',            {'Magnetic Field (LO)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-8.063 3.225 0],          ...
		'Cal0Units',       {'(MT)'},            ...
		'Cal1Consts',      [-80.63 32.25 0],          ...
		'Cal1Units',       {'(G)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Barometer = struct(...
		'Name',            {'Barometer'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [81.952 7.8 0],          ...
		'Cal0Units',       {'(KPA)'},            ...
		'Cal1Consts',      [614.84 58.52 0],          ...
		'Cal1Units',       {'(MMHG)'},            ...
		'Cal2Consts',      [24.215 2.292 0],          ...
		'Cal2Units',       {'(INHG)'})            ...

	RelativeHumidity = struct(...
		'Name',            {'Relative Humidity'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-25.81 30.43 0],          ...
		'Cal0Units',       {'(PCT)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Custom5V = struct(...
		'Name',            {'Custom 5V'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 1 0],          ...
		'Cal0Units',       {'(V)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Custom10V = struct(...
		'Name',            {'Custom 10V'},            ...
		'Channel',         10,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 1 0],          ...
		'Cal0Units',       {'(V)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	ForcePlate850N = struct(...
		'Name',            {'Force Plate (850N)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-250 250 0],          ...
		'Cal0Units',       {'(N)'},            ...
		'Cal1Consts',      [-56.202 56.202 0],          ...
		'Cal1Units',       {'(LB)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	ForcePlate3500N = struct(...
		'Name',            {'Force Plate (3500N)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-1000 1000 0],          ...
		'Cal0Units',       {'(N)'},            ...
		'Cal1Consts',      [-224.81 224.81 0],          ...
		'Cal1Units',       {'(LB)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	UVA = struct(...
		'Name',            {'UVA'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 3940 0],          ...
		'Cal0Units',       {'mw/m^2'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	UVB = struct(...
		'Name',            {'UVB'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 204 0],          ...
		'Cal0Units',       {'mw/m^2'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	ElectrodeAmplifier = struct(...
		'Name',            {'Electrode Amplifier'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-557.08 464.84 0],          ...
		'Cal0Units',       {'(mV)'},            ...
		'Cal1Consts',      [16.34 -7.78 0],          ...
		'Cal1Units',       {'(pH)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

% 	Thermocouple = struct(...
% 		'Name',            {'Thermocouple'},            ...
% 		'Channel',         5,                  ...
% 		'CalEq',           'linear',                  ...
% 		'Cal0Consts',      [-183.949 319.098 0],          ...
% 		'Cal0Units',       {'(C)'},            ...
% 		'Cal1Consts',      [-231.364 401.348 0],          ...
% 		'Cal1Units',       {'(C LO)'},            ...
% 		'Cal2Consts',      [-269.988 344.543 0],          ...
% 		'Cal2Units',       {'(C HI)'})            ...
	Thermocouple = struct(...
		'Name',            {'Thermocouple'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-197.985 326.699 0],          ...
		'Cal0Units',       {'(C)'},            ...
		'Cal1Consts',      [-231.364 401.348 0],          ...
		'Cal1Units',       {'(C LO)'},            ...
		'Cal2Consts',      [-269.988 344.543 0],          ...
		'Cal2Units',       {'(C HI)'})            ...
    
    
	Salinity = struct(...
		'Name',            {'Salinity'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 16.325 0],          ...
		'Cal0Units',       {'(ppt)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Pressure = struct(...
		'Name',            {'Pressure'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 149.77 0],          ...
		'Cal0Units',       {'(kPa)'},            ...
		'Cal1Consts',      [0 1123.36 0],          ...
		'Cal1Units',       {'(mm Hg)'},            ...
		'Cal2Consts',      [0 1.48 0],          ...
		'Cal2Units',       {'(atm)'})            ...

	Charge05V = struct(...
		'Name',            {'Charge 0.5 V'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-5.456 2.2 0],          ...
		'Cal0Units',       {'(nC)'},            ...
		'Cal1Consts',      [-0.5456 0.22 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Charge2V = struct(...
		'Name',            {'Charge 2 V'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-20.5 8.2 0],          ...
		'Cal0Units',       {'(nC)'},            ...
		'Cal1Consts',      [-2.0336 0.82 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	Charge10V = struct(...
		'Name',            {'Charge 10 V'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-96.72 39 0],          ...
		'Cal0Units',       {'(nC)'},            ...
		'Cal1Consts',      [-9.672 3.9 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	BloodPressure = struct(...
		'Name',            {'Blood Pressure'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 56.11 0],          ...
		'Cal0Units',       {'(mm Hg)'},            ...
		'Cal1Consts',      [0 7.479 0],          ...
		'Cal1Units',       {'(kPa)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	HandDynamometer = struct(...
		'Name',            {'Hand Dynamometer'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-19.2958 175.416 0],          ...
		'Cal0Units',       {'(N)'},            ...
		'Cal1Consts',      [-4.3379 39.4351 0],          ...
		'Cal1Units',       {'(lb)'},            ...
		'Cal2Consts',      [-1.9676 17.8875 0],          ...
		'Cal2Units',       {'(kg)'})            ...

	Spirometer = struct(...
		'Name',            {'Spirometer'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-17.9672 7.1869 0],          ...
		'Cal0Units',       {'(L/s)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	SoilMoisture = struct(...
		'Name',            {'Soil Moisture'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-22.74 65.29 0],          ...
		'Cal0Units',       {'(%)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	CurrentProbe12A = struct(...
		'Name',            {'Current Probe 1.2A'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [1.25 -0.5 0],          ...
		'Cal0Units',       {'(A)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	InfraredThermometernew = struct(...
		'Name',            {'Infrared Thermometer (new)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [402.5916 -84.388 0],          ...
		'Cal0Units',       {'(C)'},            ...
		'Cal1Consts',      [756.672 -151.9 0],          ...
		'Cal1Units',       {'(F)'},            ...
		'Cal2Consts',      [675.5916 -84.388 0],          ...
		'Cal2Units',       {'(K)'})            ...

	SoundLevelMeternew = struct(...
		'Name',            {'Sound Level Meter (new)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 100 0],          ...
		'Cal0Units',       {'(dB)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	CO2Lownew = struct(...
		'Name',            {'CO2 Low (new)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 2500 0],          ...
		'Cal0Units',       {'(ppm)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	CO2Highnew = struct(...
		'Name',            {'CO2 High (new)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 25000 0],          ...
		'Cal0Units',       {'(ppm)'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'(V)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	OxygenGasnew = struct(...
		'Name',            {'Oxygen Gas (new)'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 6.769 0],          ...
		'Cal0Units',       {'(PCT)'},            ...
		'Cal1Consts',      [0 676.9 0],          ...
		'Cal1Units',       {'(ppm)'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'(V)'})            ...

	VoltageProbe = struct(...
		'Name',            {'Voltage Probe'},            ...
		'Channel',         10,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 1 0],          ...
		'Cal0Units',       {'V'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'V'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'V'})            ...

	DifferentialVoltage = struct(...
		'Name',            {'Differential Voltage'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [6.25 -2.5 0],          ...
		'Cal0Units',       {'V'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'V'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'V'})            ...

	Current = struct(...
		'Name',            {'Current'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0.625 -0.25 0],          ...
		'Cal0Units',       {'A'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'V'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'V'})            ...

	TemperatureProbe = struct(...
		'Name',            {'Temperature Probe'},            ...
		'Channel',         5,                  ...
		'CalEq',           'Steinhart-Hart',                  ...
		'Cal0Consts',      [0.00102119 0.000222468 1.33*10^-07],          ...
		'Cal0Units',       {'ºC'},            ...
		'Cal1Consts',      [0.00102119 0.000222468 1.33*10^-07],          ...
		'Cal1Units',       {'ºF'},            ...
		'Cal2Consts',      [0.00102119 0.000222468 1.33*10^-07],          ...
		'Cal2Units',       {'K'})            ...

	TILight = struct(...
		'Name',            {'TI Light '},            ...
		'Channel',         0,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0.0006 0.2 0],          ...
		'Cal0Units',       {''},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'V'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'V'})            ...

	HeartRateMonitor = struct(...
		'Name',            {'Heart Rate Monitor'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 1 0],          ...
		'Cal0Units',       {'v'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'V'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'V'})            ...

	EKG = struct(...
		'Name',            {'EKG'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 1 0],          ...
		'Cal0Units',       {'mV'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'V'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'V'})            ...

	ExtraLongTempProbe = struct(...
		'Name',            {'Extra Long Temp Probe'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [-53.073 58.341 0],          ...
		'Cal0Units',       {'C'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'V'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'V'})            ...

	CO2Gas = struct(...
		'Name',            {'CO2 Gas'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 2000 0],          ...
		'Cal0Units',       {'PPM'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'V'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'V'})            ...

	OxygenGas = struct(...
		'Name',            {'Oxygen Gas'},            ...
		'Channel',         5,                  ...
		'CalEq',           'linear',                  ...
		'Cal0Consts',      [0 6.769 0],          ...
		'Cal0Units',       {'PCT'},            ...
		'Cal1Consts',      [0 1 0],          ...
		'Cal1Units',       {'V'},            ...
		'Cal2Consts',      [0 1 0],          ...
		'Cal2Units',       {'V'})            ...

end
end